import type { CustomMatcher } from 'bun:test';

// Every jest-extended matcher except `pass`/`fail` (unimplemented upstream).
// Listed explicitly because jest-extended's CustomMatchers carries a string
// index signature that makes `keyof` useless.
export type JestExtendedMatcherName =
  | 'toBeAfter'
  | 'toBeAfterOrEqualTo'
  | 'toBeArray'
  | 'toBeArrayOfSize'
  | 'toBeBefore'
  | 'toBeBeforeOrEqualTo'
  | 'toBeBetween'
  | 'toBeBigInt'
  | 'toBeBoolean'
  | 'toBeDate'
  | 'toBeDateString'
  | 'toBeEmpty'
  | 'toBeEmptyObject'
  | 'toBeEven'
  | 'toBeExtensible'
  | 'toBeFalse'
  | 'toBeFinite'
  | 'toBeFrozen'
  | 'toBeFunction'
  | 'toBeHexadecimal'
  | 'toBeInRange'
  | 'toBeInteger'
  | 'toBeNaN'
  | 'toBeNegative'
  | 'toBeNil'
  | 'toBeNumber'
  | 'toBeObject'
  | 'toBeOdd'
  | 'toBeOneOf'
  | 'toBePositive'
  | 'toBeSealed'
  | 'toBeString'
  | 'toBeSymbol'
  | 'toBeTrue'
  | 'toBeValidDate'
  | 'toBeWithin'
  | 'toChange'
  | 'toChangeBy'
  | 'toChangeTo'
  | 'toContainAllEntries'
  | 'toContainAllKeys'
  | 'toContainAllValues'
  | 'toContainAnyEntries'
  | 'toContainAnyKeys'
  | 'toContainAnyValues'
  | 'toContainEntries'
  | 'toContainEntry'
  | 'toContainKey'
  | 'toContainKeys'
  | 'toContainValue'
  | 'toContainValues'
  | 'toEndWith'
  | 'toEqualCaseInsensitive'
  | 'toEqualIgnoringWhitespace'
  | 'toHaveBeenCalledAfter'
  | 'toHaveBeenCalledBefore'
  | 'toHaveBeenCalledExactlyOnceWith'
  | 'toHaveBeenCalledOnce'
  | 'toInclude'
  | 'toIncludeAllMembers'
  | 'toIncludeAllPartialMembers'
  | 'toIncludeAnyMembers'
  | 'toIncludeMultiple'
  | 'toIncludeRepeated'
  | 'toIncludeSameMembers'
  | 'toIncludeSamePartialMembers'
  | 'toPartiallyContain'
  | 'toReject'
  | 'toResolve'
  | 'toSatisfy'
  | 'toSatisfyAll'
  | 'toSatisfyAny'
  | 'toStartWith'
  | 'toThrowWithMessage';

export type JestExtendedMatcher = CustomMatcher<unknown, unknown[]>;

// bun:test declares MatcherContext without exporting it; recover it from the
// `this` parameter of the exported CustomMatcher type.
export type MatcherContext = ThisParameterType<JestExtendedMatcher>;
